<Project>
	<PropertyGroup>
		<!--Global settings -->
		<nullable>enable</nullable>
		<ImplicitUsings>true</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<FileVersion>$([System.DateTime]::UtcNow.Year).$([System.DateTime]::UtcNow.ToString("MMdd")).$([System.DateTime]::UtcNow.ToString("HHmm")).$([System.DateTime]::UtcNow.ToString("ssfff"))</FileVersion>

		<!-- Warnings -->
		<WarningsAsErrors>CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8620;CS8621;CS8622;CS8625;CS8764;CS8765;CS8766;CS8767</WarningsAsErrors>
		<NoWarn>CS1685;IDE0028;IDE0290</NoWarn>
		<WarningLevel>5</WarningLevel>

		<Version>1.0.0-prerelease-1</Version>
	</PropertyGroup>
</Project>
